server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/OrderManagementSystem
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
      dialect: org.hibernate.dialect.MySQL5Dialect
    properties:
      hibernate:
        show_sql: true
  devtools:
    restart:
      enabled: true
  application:
    name: user-service
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka