# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Integration

on:
  push:
    branches:
      - "darshan/feature/user-service"
  pull_request:
    branches:
      - "development"
      - "production"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Starting MySQL server
        uses: mirromutth/mysql-action@v1.1
        with:
          mysql database: 'OrderManagementSystem'
          mysql root password: 'password' # Required if "mysql user" is empty, default is empty. The root superuser password
          mysql user: 'root'
          mysql password: 'password'
      - name: Build with Maven - discovery-server-app
        run: mvn -B package --file discovery-server-app/pom.xml
      - name: Build with Maven - user-service-app
        run: mvn -B package --file user-service-app/pom.xml
      - name: Starting discovery-server
        run: java -jar discovery-server-app/target/discovery-server-app-0.0.1-SNAPSHOT.jar &
      - run: sleep 10
      - name: Starting user-service
        run: java -jar user-service-app/target/user-service-app-0.0.1-SNAPSHOT.jar &
      - run: sleep 10
      - name: Testing API endpoints of discovery-server
        uses: matt-ball/newman-action@master
        with:
          collection: ./discovery-server-app/DiscoveryServer.postman_collection.json
      - name: Testing API endpoints of user service
        uses: matt-ball/newman-action@master
        with:
          collection: ./user-service-app/UserService.postman_collection.json
          environment: ./OrderManagementSystem.postman_environment.json
      - run: sleep 5
      - name: Shutting down discovery server
        run: kill -9 `lsof -i:8761 -t`
      - name: Shutting down user service
        run: kill -9 `lsof -i:8081 -t`